[package]
name = "funnelweb-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.199", features = ["derive"] }
toml = "0.8.12"

[dev-dependencies]
insta = { version = "1.38" }

[features]
default = ["alloc", "std"]
std = []
alloc = []